
CREATE TABLE Sach (
    MaSach INT PRIMARY KEY AUTO_INCREMENT,
    TenSach VARCHAR(255) NOT NULL,
    TacGia VARCHAR(100),
    TheLoai VARCHAR(50),
    NamXuatBan INT
);

CREATE TABLE DocGia (
    MaDocGia INT PRIMARY KEY AUTO_INCREMENT,
    HoTen VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255),
    SoDienThoai VARCHAR(20),
    Email VARCHAR(100)
);

CREATE TABLE Muon (
    MaMuon INT PRIMARY KEY AUTO_INCREMENT,
    MaDocGia INT NOT NULL,
    MaSach INT NOT NULL,
    NgayMuon DATE NOT NULL,
    NgayTra DATE,
    FOREIGN KEY (MaDocGia) REFERENCES DocGia(MaDocGia),
    FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
);
